management.endpoints.web.exposure.include=*
management.security.enabled=true
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=10s
spring.task.scheduling.shutdown.await-termination=true
spring.task.scheduling.shutdown.await-termination-period=10s
spring.task.execution.shutdown.await-termination=true
spring.task.execution.shutdown.await-termination-period=10s
